//tealium universal tag - utag.2052 ut4.0.201703131314, Copyright 2017 Tealium.com Inc. All Rights Reserved.
var _sf_startpt=_sf_startpt||(new Date()).getTime();var _sf_async_config={};_sf_async_config.uid=47635;_sf_async_config.domain='guampdn.com';_sf_async_config.useCanonical=(("true"=="true")?true:false);try{(function(id,loader,u){try{u=utag.o[loader].sender[id]={}}catch(e){u=utag.sender[id]};u.ev={'view':1};u.qsp_delim='&';u.kvp_delim='=';u.initialized=false;u.base_url='//static.chartbeat.com/js/chartbeat_pub.js';u.map={};u.extend=[function(a,b){if(b.partner_type||(b.contenttype==='video'&&!(/video|videos/).test(window.location.pathname))){return false;}
if(typeof(b.noinitialanalytics)!=='undefined'){try{if(b.noinitialanalytics.toLowerCase()==="true"){return false;}}catch(e){}}
if(typeof(b.embedded)!=='undefined'){try{if(b.embedded.toLowerCase()==='true'){return false;}}catch(e){}}},function(a,b){var __domain=document.domain;var __isCommunity=false;var _checkDomains=['www.brookfield-elmgrovenow.com','www.greenfield-westallisnow.com','www.lakecountrynow.com','www.metroparentmagazine.com','www.muskego-newberlinnow.com','www.mynorthshorenow.com','www.mynorthwestnow.com','www.myozaukeenow.com','www.mysouthnow.com','www.mysouthshorenow.com','www.waukeshanow.com','www.wauwatosanow.com','www.wisfarmer.com'];var _checkDomainsLen=_checkDomains.length;for(var i=0;i<_checkDomainsLen;i++){if(_checkDomains[i]===__domain){__domain='mycommunitynow.com';__isCommunity=true;break;}}
if(typeof _sf_async_config!=="undefined")
{_sf_async_config.sections=b.ssts.replace(/\:/g,',');_sf_async_config.authors=b.byline.split(',')[0].toLowerCase();if(__isCommunity){_sf_async_config.domain=__domain;}
_sf_async_config.type=b.contenttype;_sf_async_config.sponsorName="";if(typeof stateManager!="undefined"&&typeof stateManager.getActivePageInfo!="undefined"){if(stateManager.getActivePageInfo().sponsored_series){_sf_async_config.sponsorName=stateManager.getActivePageInfo().sponsorname||'';}};}
if(typeof pSUPERFLY!=="undefined"&&b.eventtype!=="slide:change"){pSUPERFLY.virtualPage(location.pathname,document.title);_sf_startpt=(new Date()).getTime();}},function(a,b){if(b.user_status){var _cbq=window._cbq||[];_cbq.push(['_acct',b.user_status]);}},function(a,b){if(b.geography){var _cbq=window._cbq||[];_cbq.push(['_geography',b.geography]);}},function(a,b){if(b.subRegion){var _cbq=window._cbq||[];_cbq.push(['_sub_region',b.subRegion]);}},function(a,b){if(b.marketDivision){var _cbq=window._cbq||[];_cbq.push(['_division',b.marketDivision]);}}];u.send=function(a,b,c,d,e,f){if(u.ev[a]||typeof u.ev.all!='undefined'){for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};for(d in utag.loader.GV(u.map)){if(typeof b[d]!='undefined'&&b[d]!=''){e=u.map[d].split(',');for(f=0;f<e.length;f++){_sf_async_config[e[f]]=b[d];}}}
if(!u.initialized){u.initialized=true;window._sf_endpt=(new Date()).getTime();u.head=document.getElementsByTagName('head')[0];u.scr=document.createElement('script');u.scr.src=u.base_url;u.head.appendChild(u.scr);}}}
try{utag.o[loader].loader.LOAD(id)}catch(e){utag.loader.LOAD(id)}})('2052','gci.guampdn');}catch(e){}
