var updatingImage="http://cdn.phys.org/img/updating.gif";
(function(d){var c=function(a){this._options={checkOnLoad:!1,resetOnEnd:!1,loopCheckTime:50,loopMaxNumber:5,baitClass:"pub_300x250 pub_300x250m pub_728x90 text-ad textAd text_ad text_ads text-ads text-ad-links",baitStyle:"width: 1px !important; height: 1px !important; position: absolute !important; left: -10000px !important; top: -1000px !important;",debug:!1};this._var={version:"3.2.0",bait:null,checking:!1,loop:null,loopNumber:0,event:{detected:[],notDetected:[]}};void 0!==a&&this.setOption(a);
var b=this;a=function(){setTimeout(function(){!0===b._options.checkOnLoad&&(!0===b._options.debug&&b._log("onload->eventCallback","A check loading is launched"),null===b._var.bait&&b._creatBait(),setTimeout(function(){b.check()},1))},1)};void 0!==d.addEventListener?d.addEventListener("load",a,!1):d.attachEvent("onload",a)};c.prototype._options=null;c.prototype._var=null;c.prototype._bait=null;c.prototype._log=function(a,b){console.log("[BlockAdBlock]["+a+"] "+b)};c.prototype.setOption=function(a,
b){if(void 0!==b){var c=a;a={};a[c]=b}for(var d in a)this._options[d]=a[d],!0===this._options.debug&&this._log("setOption",'The option "'+d+'" he was assigned to "'+a[d]+'"');return this};c.prototype._creatBait=function(){var a=document.createElement("div");a.setAttribute("class",this._options.baitClass);a.setAttribute("style",this._options.baitStyle);this._var.bait=d.document.body.appendChild(a);this._var.bait.offsetParent;this._var.bait.offsetHeight;this._var.bait.offsetLeft;this._var.bait.offsetTop;
this._var.bait.offsetWidth;this._var.bait.clientHeight;this._var.bait.clientWidth;!0===this._options.debug&&this._log("_creatBait","Bait has been created")};c.prototype._destroyBait=function(){d.document.body.removeChild(this._var.bait);this._var.bait=null;!0===this._options.debug&&this._log("_destroyBait","Bait has been removed")};c.prototype.check=function(a){void 0===a&&(a=!0);!0===this._options.debug&&this._log("check","An audit was requested "+(!0===a?"with a":"without")+" loop");if(!0===this._var.checking)return!0===
this._options.debug&&this._log("check","A check was canceled because there is already an ongoing"),!1;this._var.checking=!0;null===this._var.bait&&this._creatBait();var b=this;this._var.loopNumber=0;!0===a&&(this._var.loop=setInterval(function(){b._checkBait(a)},this._options.loopCheckTime));setTimeout(function(){b._checkBait(a)},1);!0===this._options.debug&&this._log("check","A check is in progress ...");return!0};c.prototype._checkBait=function(a){var b=!1;null===this._var.bait&&this._creatBait();
if(null!==d.document.body.getAttribute("abp")||null===this._var.bait.offsetParent||0==this._var.bait.offsetHeight||0==this._var.bait.offsetLeft||0==this._var.bait.offsetTop||0==this._var.bait.offsetWidth||0==this._var.bait.clientHeight||0==this._var.bait.clientWidth)b=!0;if(void 0!==d.getComputedStyle){var c=d.getComputedStyle(this._var.bait,null);if("none"==c.getPropertyValue("display")||"hidden"==c.getPropertyValue("visibility"))b=!0}!0===this._options.debug&&this._log("_checkBait","A check ("+
(this._var.loopNumber+1)+"/"+this._options.loopMaxNumber+" ~"+(1+this._var.loopNumber*this._options.loopCheckTime)+"ms) was conducted and detection is "+(!0===b?"positive":"negative"));!0===a&&(this._var.loopNumber++,this._var.loopNumber>=this._options.loopMaxNumber&&this._stopLoop());if(!0===b)this._stopLoop(),this._destroyBait(),this.emitEvent(!0),!0===a&&(this._var.checking=!1);else if(null===this._var.loop||!1===a)this._destroyBait(),this.emitEvent(!1),!0===a&&(this._var.checking=!1)};c.prototype._stopLoop=
function(a){clearInterval(this._var.loop);this._var.loop=null;this._var.loopNumber=0;!0===this._options.debug&&this._log("_stopLoop","A loop has been stopped")};c.prototype.emitEvent=function(a){!0===this._options.debug&&this._log("emitEvent","An event with a "+(!0===a?"positive":"negative")+" detection was called");a=this._var.event[!0===a?"detected":"notDetected"];for(var b in a)if(!0===this._options.debug&&this._log("emitEvent","Call function "+(parseInt(b)+1)+"/"+a.length),a.hasOwnProperty(b))a[b]();
!0===this._options.resetOnEnd&&this.clearEvent();return this};c.prototype.clearEvent=function(){this._var.event.detected=[];this._var.event.notDetected=[];!0===this._options.debug&&this._log("clearEvent","The event list has been cleared")};c.prototype.on=function(a,b){this._var.event[!0===a?"detected":"notDetected"].push(b);!0===this._options.debug&&this._log("on",'A type of event "'+(!0===a?"detected":"notDetected")+'" was added');return this};c.prototype.onDetected=function(a){return this.on(!0,
a)};c.prototype.onNotDetected=function(a){return this.on(!1,a)};d.BlockAdBlock=c;void 0===d.blockAdBlock&&(d.blockAdBlock=new c({checkOnLoad:!0,resetOnEnd:!0}))})(window);
$(document).ready(function(){$.fx.off=$.isMobile();signIn(mid);mainNav();function b(a,b){b.click(function(){a.removeClass("current");$(this).addClass("current");$(".text_l").hide();$(".text_r").show();return!1});a.click(function(){b.removeClass("current");$(this).addClass("current");$(".text_r").hide();$(".text_l").show();return!1})}imgDefer();if(!$.isMobile()){$("a[data-rel=tlp]").each(function(){$(this).parentsUntil(".news-box").balloon({position:"left",delay:300,offsetX:-5,contents:$("#tlp"+$(this).attr("id")).html(),css:{width:"230px",padding:"10px",
opacity:"1"},showAnimation:function(a){this.fadeIn(a)}})});var a=$("<a>").attr("id","back-top").attr("href","").html("back to top").click(function(){$("body,html").animate({scrollTop:0},500);return!1}).hide();$("#wrapper").append(a);$(window).scroll(function(){100<$(window).scrollTop()?a.fadeIn(750):a.fadeOut(500)})}"1"==$.cookie("physMob")&&popupHint("<a href=\"http://m.phys.org/\" onclick=\"return $.cookie('pdaPhysOrg',0,{path: '/',domain:'.phys.org'});\">To switch back to the mobile-friendly view, click here</a>");
$("a[href=#top]").click(function(){$("html, body").animate({scrollTop:0},"slow");return!1});
if($("#jxad").length){var pageJxAd=2,jxad=$("#jxad"),jx=$("<a>").attr("href","#").addClass("inl-button").html("load more"),categ=jxad.data("category");jxad.html(jx);jx.click(function(){var a=$(this);a.hide();$.get("/ajax/load-more/?page="+pageJxAd+"&categ="+categ,function(b){jxad.before(b);a.show();setTimeout(imgDefer,0)});pageJxAd++;try{_gaq.push(["_trackEvent","ajax","load","main page"])}catch(b){}return!1})};
if($("#other-block").length){$("#other-nav").attr("data-count",0);var d=function(a,b){$("#other-page > li > a[data-pn="+a+"]").removeClass("active");$("#other-page > li > a[data-pn="+b+"]").addClass("active");$("#other-block").css("opacity",.4);$("#other-block").load("/ajax/other-news/page"+(parseInt(b)+1)+".html",null,function(){$("#other-block").css("opacity",1);setTimeout(imgDefer,0)});$("#other-nav").attr("data-count",b)};$("#nav-l").click(function(){var a=
parseInt($("#other-nav").attr("data-count")),b=parseInt(1>a?5:a-1);d(a,b);return!1});$("#nav-r").click(function(){var a=parseInt($("#other-nav").attr("data-count")),b=parseInt(4<a?0:a+1);d(a,b);return!1});$("#other-page > li > a").click(function(){var a=parseInt($("#other-nav").attr("data-count")),b=parseInt($(this).attr("data-pn"));d(a,b);return!1})}srchParse();var e=$(".header_l").find("a"),f=$(".header_r").find("a");1100>=$(window).width()&&b(e,f);$(window).resize(function(){1100>=$(window).width()?
b(e,f):($(".text_r, .text_l").show(),e.off("click"),f.off("click"))})});function imgDefer(){$("img[rel*=async]").each(function(){$(this).attr("data-source")&&($(this).attr("src",$(this).attr("data-source")),$(this).removeAttr("data-source"),$(this).removeClass("hidden"))})}
function signIn(b){var a=$("#scx_profile"),c=$("#dropdown-profile");b&&0!=b&&($("#scx_uname").html(userNick),0<parseInt(newPM)&&$("#counter-profile").html(newPM).show(),$("#login-box").hide(),$("#profile-box").show());a.off("click").click(function(){a.toggleClass("current");c.slideToggle(250,function(){a.hasClass("current")&&c.find("input[name=email]").focus()});if(a.hasClass("current")){var b=$("<div></div>").addClass("simplemodal-overlay").attr("id","simplemodal-overlay");$("#wrapper").append(b);
b.css({position:"absolute",left:0,top:99,width:"100%",height:$("#wrapper").height()-100,opacity:0,"z-index":2147483645});setTimeout(function(){b.css({visibility:"visible",opacity:.6,transition:"opacity .25s ease-in-out","-webkit-transition":"opacity .25s ease-in-out"})},0);c.click(function(a){a.stopPropagation()});$("#wrapper").on("click.scxprofile",function(){$("#simplemodal-overlay").remove();a.removeClass("current");c.hide()})}else $("#simplemodal-overlay").remove(),$("#wrapper").off("click.scxprofile");
return!1})}
function popupHint(e,b,c){var a=!0;b&&$.cookie("physorgHint")==b&&(a=!1);c="undefined"===typeof c?30:c;navigator.userAgent.indexOf("iPad");navigator.userAgent.indexOf("Android 3.");if(a){var a=$("<div></div>").addClass("notice-inside"),d=parseInt($("#container").css("padding-top"));$("<h6>"+e+"</h6>").appendTo(a);$("<a>").addClass("close-notice").attr("href","").click(function(a){a.preventDefault();$(this).hide();$(this).closest(".notice").slideUp(function(){$("#container").css("padding-top",d)});
b&&$.cookie("physorgHint",b,{path:"/",expires:c})}).appendTo(a);$("#container").css("padding-top",d+32);$("<section></section>").addClass("notice").append(a).prependTo($("#header"))}};
function mainNav(){var b="",a=null,c=function(a){b&&b.removeClass("current");b=""},d=function(a){a[0]!=b[0]&&""!=b&&b.removeClass("current");a.addClass("current");b=a;e(a.find("li.full-sub-nav:first-child"))},e=function(a){var b=a.find("a").data("href");a.children("ul").show();0!=a.find("ul[data-rel=placeholder]").length&&(k=1200<$(window).width()?8:6,$.get("/ajax"+b+"?limit="+k).done(function(b){a.children("ul").replaceWith(b)}))},f=window.navigator.msPointerEnabled?"MSPointerDown":"touchend",h=
!1,g=!0;$("#wrapper").click(c);$("#main-nav > ul > li ").has("ul").on(f,function(b){g=0<$(b.target).parents(".dropdown-wrap").length;if(!g){clearTimeout(a);var c=$(this).children("ul.dropdown-wrap");setTimeout(function(){d(c)},0);h=!0;b.stopPropagation()}}).hover(function(c){clearTimeout(a);var e=$(this).children(".dropdown-wrap");a=""!=b?setTimeout(function(){d(e)},150):setTimeout(function(){e[0]!=b[0]&&(e.addClass("current"),b="",d(e))},500)},function(){h||(clearTimeout(a),a=setTimeout(c,300))}).click(function(a){return g});
$(".full-sub-nav").addClass("full-sub-nav").append('<ul data-rel="placeholder" class="hidden"><li></li></ul>');$(".list-category").menuAim({activate:function(a){e($(a))},deactivate:function(a){$(a).find("ul").hide()}})}function ShowAlert(b){return $.modal('<div class="window_contents">'+b+"</div>")}
function tabShow(b){clearTimeout(tabTmId);var a="/ajax/sort/"+b+"/";tabShow.arguments[2]&&(a+="?tpl="+tabShow.arguments[2]);tabShow.arguments[4]&&(a+="&skip=1");$("#"+tabMode)&&$("#"+tabMode).removeClass("current");tabMode="tab-"+b;$("#"+tabMode).addClass("current");$("#tabs").css("opacity",.4);$("#tabs").load(a,null,function(){$("#tabs").css("opacity",1);setTimeout(imgDefer,0)});return!1}
function tabRotate(){var b=["editorials","commented","popular","physicsforums"],a=Math.floor(Math.random()*b.length);if(0==a||a>b.length)return!1;$("#"+tabMode)&&$("#"+tabMode).removeClass("current");tabMode="tab-"+b[a];$("#"+tabMode)&&$("#"+tabMode).addClass("current");tabShow(b[a]);return!0}
function asyncjs(b){var a=document.createElement("script");a.type="text/javascript";a.async=!0;1<arguments.length&&(a.id=arguments[1]);a.src=b;var c=document.getElementsByTagName("script")[0];c.parentNode.insertBefore(a,c);return a}
function ABhint(){if("undefined"!==typeof googletag)popupHint('It appears that you are currently using <b>Ad Blocking</b> software. What are the consequences? <a href="https://sciencex.com/help/adblock/">Click here</a> to learn more.')}if("undefined"===typeof blockAdBlock)ABhint();else blockAdBlock.onDetected(ABhint);
function srchParse(){var b,a;if(b=document.referrer.replace(/^[^\?]+\??/,"").replace(/#[^#]*$/,"")){for(var c=b.split(/[&;]/),d=0;d<c.length;d++)if(b=RegExp(/^((enc)?q(uery)?|p)=(.*?)$/).exec(c[d]))a=b[4];a&&(a=unescape(a).replace(/[\+]+/g," "),popupHint('Find more articles on <a href="/search/?search='+escape(a)+'">'+a+"</a>"))}}function google_ad_request_done(b){};
