$(document).ready(function(){1200>$(window).width()&&$("#slick-social").addClass("slick-bottom");600>$("article").height()&&$("#slick-social").addClass("slick-bottom");$(window).resize(function(){1200>$(window).width()&&$("#slick-social").sticky("disable")});for(var b=$("article"),d=$("aside.sidebar"),f=b.height(),a=d.height();f<a-50;)d.children(".sidebar-box").last().remove(),f=b.height(),a=d.height();$(".image-block-caption").shorten();(function(){var a=$("#news-holder");a.height();$("#news-holder .news-col").height(380);
a.height(440);a.append('<footer id="n-overlay"><a id="n-more" href="#"></a></footer>');$("#n-more").on("click",function(){$("#n-overlay").hide();$("#news-holder .news-col").height("auto");a.animate({height:440},300,function(){a.height("auto")});return!1})})();$("#inl-rel-href").click(function(){$("#news-holder").scrollTo();return!1});$("#slick-social").hasClass("slick-bottom")||$("#slick-social").sticky({offsetX:0,guard:!0});$(document).on("copy",addLink);$("#sfb").click(function(){openDialog("/ajax/addFeedback/"+
nid+"/","<h4>Thank you for taking your time to send in your valued opinion to Phys.org editors. </h4> <br/>              <p>You can be assured our editors closely monitor every feedback sent and will take appropriate actions. <p>             <p>Your opinions are important to us. We do not guarantee individual replies due to extremely high volume of correspondence. </p>");return!1});$("#tl-email, #mail-flip").click(function(){openDialog("/ajax/sendEmail/"+nid+"/");return!1});$("#fb-flip").click(function(){FB.ui({method:"share",
display:"popup",href:window.location.href},function(a){});return!1});(function(){if(!$.isMobile()){var a=$("#shares"),b=a.text(),g=$(window).height(),f=a.offset().top;$(window).on("scroll.shares",function(){a.text("0");0>f-$(window).scrollTop()-g- -10&&($({Counter:0}).animate({Counter:b},{duration:1500,easing:"swing",step:function(){a.text(Math.ceil(this.Counter))}}),$(window).off("scroll.shares"))})}})();$("a[rel=lightbox]").click(function(){var a=$(this);a.html();var b=a.attr("href"),f=a.attr("title"),
d=new Image;$(d).load(function(){var b=$("<div>").addClass("image_contents").append($(d));if(f){var k=d.width,k=$('<div class="window_desc">'+f+"</div>").width(k);b.append(k)}$.modal(b,{fixed:!1});a.removeClass("loading")});a.addClass("loading");d.src=b;try{_gaq.push(["_trackEvent","lightbox","view",b])}catch(l){}return!1});$("#addFav").click(function(){return 0==addFav(nid)});asyncjs("//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=163850683679377&version=v2.9","facebook-jssdk");asyncjs("https://platform.twitter.com/widgets.js");
asyncjs("https://apis.google.com/js/plusone.js");$(asyncjs("//assets.pinterest.com/js/pinit.js")).attr("data-pin-hover",!0);$("#sc-reddit").html($("<iframe/>").attr({src:"//www.redditstatic.com/button/button2.html?width=51&url="+window.location.href,height:69,width:51,scrolling:"no",frameborder:0}));setTimeout(function(){$(".slick-bottom").addClass("flex-box")},0);$("#news-extra").lazyload(function(){$.ajax({type:"POST",url:"/ajax/story/",data:{uids:uids,categ:categ},success:function(a){$("#news-extra").replaceWith(a);
setTimeout(imgDefer,0)}})});b=$(".article-block");d=$(".bf-banner");d.css({"margin-left":b.css("margin-left"),"padding-left":b.css("padding-left")});0<b.position().left&&d.css({"margin-left":b.position().left+"px"})});
function rateit(b,d){$.ajax("/votes/?submit=true&newsid="+b+"&rank="+d,{beforeSend:function(){$("#nwvoteTp").animate({"margin-top":"-26px"},300)}}).done(function(a){var d=$(a).find("code").text(),h=$(a).find("rank").text();a=$(a).find("total").text();200==d?$("#rank").children("h6").hide().html(f(h,a)).fadeIn():(ShowAlert('<div class="msg">Your request cannot be processed at this time</div>'),$("#nwvoteTp").css("margin-top",0));try{_gaq.push(["_trackEvent","ajax","rate",b])}catch(g){}});var f=function(a,
b){if(0==a)return"not rated yet";var d=a+" /5 ("+b+" vote";return 1<b?d+"s)":d+")"}}function addFav(b){if("0"!=mid&&""!=mid)$.ajax("/ajax/addFav/"+b+"/",{method:"get"}).done(function(){ShowAlert('<h5>Saved to your Science X account</h5><br/>                <p>You may always view/manage your bookmarks from your <a href="https://sciencex.com/profile/favorites/">Science X account</a></p>');return!0});else return!1}
var Comments=function(b,d){var f=$(".com").length,a=null,k=function(e){$.get("/ajax/comments/?code=form-add").done(function(c){c=$(c);a=c.filter("form");c.find("input[name=nid]").val(b);c.find("#input-comment").keyup(function(){n($(this).val(),1E3)});c.find("#input-comment").keydown(function(){n($(this).val(),1E3)});c.find("#cm-follow").attr("checked","on"==follow).switchbox().change(function(){var a=$(this);$.post("/ajax/comments/","status=follow&nid="+b).done(function(c){var e=$(c).find("code").text();
200==e?(a.attr("checked",!0),follow="on"):300==e?(a.attr("checked",!1),follow=""):400==e&&(c=$(c).find("msg").text(),ShowAlert('<div class="window_contents msg">'+c+"</div>"))})});a.submit(function(c){c.preventDefault();a.find("[name=sort]").val(sort);m().done(function(a){g();"DESC"==sort&&$("#comments").scrollTo()})});c.find("#com-cancel").click(t);e.html(c)})},h=function(e,c){var b=function(){m().done(function(a){a=$(a);mid=a.find("mid").text();userNick=a.find("nickname").text();signIn(mid);g()});
return!1};c?(a=e.find("form"),a.submit(b)):$.get("/ajax/comments/?code=form-login").done(function(c){c=$(c);a=c.find("form");a.submit(b);e.html(c)})},g=function(){$.ajax("/ajax/comments/?code=view&format=html&newsid="+b+"&sort="+sort+"&filter="+fltthres,{beforeSend:function(){$("#pageCmnt").html(updIMG)},complete:function(){$("#pageCmnt").html("")},success:function(a){a=$(a).find("#comments").html();$("#comments").html(a);setTimeout(l,0)}});fltthres?$("#fltCmnt").addClass("com-rank-on"):$("#fltCmnt").removeClass("com-rank-on");
p()},r=function(a){$.get("/ajax/comments/?code=COM&format=html&cid="+a).done(function(c){if(c=$(c).find("text").text())$("#cm_"+a).removeClass("com-sup"),$("#cm_"+a).html(c)})},l=function(){f=$(".com").length;var a="",a=0<f?f+" comment"+(1<f?"s":""):"User comments";$("#nwcc").html(a);$("section[data-type=comment]").each(function(){var a=$(this).attr("data-cid"),b=$(this).find(".com-footer");$(this).find("a[href=#display]").click(function(){$(this).hide(0);var a=$(this).attr("data-cid");r(a);return!1});
var e=$('<a href="#">Report</a>').click(function(){u(a);return!1});b.prepend(e);"on"==$(this).attr("data-edit")&&(e=$('<a href="#">Edit</a>').click(function(){v(a);return!1}),b.prepend(e));"on"==$(this).attr("data-quote")&&(e=$('<a href="#">Quote</a>').click(function(){w(a);return!1}),b.prepend(e));"0"!=mid&&""!=mid&&(e="on"==$(this).attr("data-ignore")?$('<a href="#">Remove from ignore list</a>').click(function(){q(a,0);return!1}):$('<a href="#">Ignore user</a>').click(function(){q(a,1);return!1}),
b.prepend(e));if("on"==$(this).attr("data-rate")){b=$(this).find(".com-rating");b.addClass("star-rating small-star");b.html("");var d=["one-star","two-stars","three-stars","four-stars","five-stars"];e="";$(d).each(function(c){e=$('<a href=""></a>').addClass(d[c]).click(function(){var e=c+1;b.animate({width:16},300,function(){$(this).addClass("com-rating-placeholder")});b.children().remove();$.get("/ajax/comments/?code=RATE&cid="+a+"&rank="+e).done(function(c){var b=$(c).find("msg").text();b?ShowAlert(b):
(b=$(c).find("rank").text(),c=$(c).find("votes").text(),$("#rk_"+a).hide().html(0==b?"not rated yet":b+" /5 ("+c+")").fadeIn())});return!1});var f=$("<li></li>").append(e);b.append(f)})}}).on("touchend",function(){$(this).children(".com-footer").css("visibility","visible");return!1})},m=function(){var b=!0,c=$.Deferred();$("[data-required=1]").each(function(){$(this).val()?$(this).removeClass("com-input-err"):($(this).addClass("com-input-err"),b=!1)});if(b){var d=a.serialize();$.post("/ajax/comments/",
d).done(function(a){var b=$(a).find("code").text(),e=$(a).find("msg").text();200!=b?(ShowAlert('<div class="window_contents msg">'+e+"</div>"),c.notify(a)):c.resolve(a)})}return c},u=function(a){$.modal('<div class="window_contents"><form name="repCmnt"><fieldset>                   <p>Report this comment as spam, offensive or inappropriate?</p>                   <p class="button-wrap"><button type="submit">report</button></p>                  <input type="hidden" name="code" value="FLAG">                   <input type="hidden" name="cid" value="">                 </fieldset></form></div>',
{onShow:function(){var c=this.d.data;c.find("form").submit(function(){$(this).find("[name=cid]").val(a);var b=$(this).serialize();$.get("/ajax/comments/",b).done(function(a){a=$(a).find("msg").text();c.html('<div class="window_contents msg">'+a+"</div>")});return!1})}})},v=function(b){$.get("/ajax/comments/?code=COM&cid="+b).done(function(c){300==$(c).find("code").text()?ShowAlert($(c).find("msg").text()):(a.scrollTo(),c=$(c).find("text").text(),$("#addtitle").html("Edit"),a.find("[name=cid]").val(b),
a.find("[name=status]").val("edit"),a.find("textarea").val(c))})},w=function(b){$.get("/ajax/comments/?code=COM&cid="+b).done(function(c){var b=$(c).find("text").text();""!=b&&(c=a.find("textarea"),b=(c.val()?c.val()+"\r\n\r\n":"")+"[q]"+b+"[/q]\r\n",c.val(b),c.focus(),c.scrollTo())})},q=function(a,b){b=b?"1":"0";var c=$.modal('<div class="window_contents"><form name="repCmnt"><fieldset>                   <p>'+("1"==b?"Add user to your personal ignored list and hide any posts from that user?":"Remove user from your personal ignore user list?")+
'</p>                   <p class="button-wrap"><button type="submit">Ok</button></p>                  <input type="hidden" name="code" value="ignore">                   <input type="hidden" name="cid" value="">                   <input type="hidden" name="state" value="">                 </fieldset></form></div>',{onShow:function(){this.d.data.find("form").submit(function(){$(this).find("[name=cid]").val(a);$(this).find("[name=state]").val(b);var e=$(this).serialize();$.get("/ajax/comments/",e).done(g);
c.close();return!1})}})},t=function(){$("#addtitle").html("Add");a.find("[name=cid]").val(0);a.find("[name=status]").val("new");a.find("textarea").val("");return!1},p=function(b){var c=$("#postbox");"0"==cmperm?(c.html('<div class="box-content centered rank-filter">Commenting is closed for this article.</div>'),a=null):"0"!=mid&&""!=mid?k(c):h(c,b)},n=function(a,b){parseInt(a.length)>b&&$("#input-comment").val(a.substring(0,b-1));$("#cmChCnt").html(b-parseInt(a.length))};$("#sortCmnt").click(function(a){"ASC"==
sort?(sort="DESC",sortTXT="oldest first"):(sort="ASC",sortTXT="newest first");g();$("#sortCmnt").html(sortTXT);return!1});$("#thrCmnt").slideControl({target:$("#fltCmnt"),onChange:function(a){fltthres=(fltthres=0,a);g()}});$("#fltCmnt").click(function(a){a=$("#thrCmnt").val();fltthres=fltthres?0:a;g();return!1});$("#cmtHidden").click(function(){g();return!1});$("#closeCmt").click(function(){$(".coments-content").html('<p>Comment preferences can be saved for registered accounts. Set your preferences <a href="https://sciencex.com/profile/comments/?code=settings" rel="nofollow">here</a>.                                                <p>Registered members  receive other benefits, as well. <a href="https://sciencex.com/help/account/" rel="nofollow">Read more</a>.');
$(this).hide();return!1});l();p(!0)};
function addLink(){var b;if("undefined"!=typeof window.getSelection&&(b=window.getSelection(),!(100>b.toString().length))){var d=window.getSelection().getRangeAt(0),f='<br /><br /> Read more at: <a href="'+document.location.protocol+"//"+document.location.host+document.location.pathname+'#jCp">'+document.location.protocol+"//"+document.location.host+document.location.pathname+"#jCp</a>",a=$("<div></div>").css({position:"absolute",left:"-99999px"}).html(b.getRangeAt(0).cloneContents()).append($(f));$("body").append(a);
b.selectAllChildren(a[0]);setTimeout(function(b){a.remove();window.getSelection().removeAllRanges();window.getSelection().addRange(d)},0)}}
function openDialog(b,d){var f=function(a,d){a.find("form")&&a.find("button").click(function(){var h=!0;a.find("input[required]").each(function(){var a=$(this),b=a.val();if(""==$.trim(b))return h=!1,a.showBalloon({position:"bottom",minLifetime:0,contents:"This field is required",css:{zIndex:"2147483644"}}),setTimeout(function(){a.hideBalloon()},1200),!1});if(!h)return!1;$(this).attr("disabled","disabled");var g=a.find("form").serialize();$.post(b,g).done(function(b){a.slideUp(300,function(){var a=
d?d:b;$(this).html('<div class="window_contents msg">'+a+"</div>").slideDown();f($(this))})});return!1})};$.get(b).done(function(a){$.modal('<div class="window_contents">'+a+"</div>",{onShow:function(){f(this.d.data,d)}})})};