/**
 * Constants
 */
F1000.Globals = {
  ArticleTypes: {
    ANTIBODY_VALIDATION_ARTICLE: 'Antibody Validation Article',
    CASE_REPORT: 'Case Report',
    CLINICAL_PRACTICE_ARTICLE: 'Clinical Practice Article',
    COMMENTARY: 'Commentary',
    CORRESPONDENCE: 'Correspondence',
    DATA_ARTICLE: 'Data Article',
    DATA_NOTE: 'Data Note',
    EDITORIAL: 'Editorial',
    F1000_FACULTY_CRITIQUE: 'F1000 Faculty Critique',
    METHOD_ARTICLE: 'Method Article',
    OBSERVATION_ARTICLES: 'Observation Article',
    OPEN_LETTER: 'Open Letter',
    OPINION_ARTICLE: 'Opinion Article',
    RESEARCH_ARTICLE: 'Research Article',
    RESEARCH_NOTE: 'Research Note',
    RETRACTION: 'Retraction',
    REVIEW: 'Review',
    SHORT_RESEARCH_ARTICLE: 'Short Research Article',
    SINGLE_FIGURE_NOTE: 'Single-Figure Note',
    SOFTWARE_TOOLS: 'Software Tool Article',
    STUDY_PROTOCOL: 'Study Protocol',
    SYSTEMATIC_REVIEW: 'Systematic Review',
    THOUGHT_EXPERIMENT: 'Thought Experiment',
    WEB_TOOLS: 'Web Tool'
  },
  Classes: {
    CHECKED: 'is-checked',
    DISABLED: 'is-disabled',
    EDIT: 'is-edit',
    HIDDEN: 'is-hidden',
    INDETERMINATE: 'is-indeterminate',
    NEW: 'is-new',
    OPEN: 'is-open',
    SELECTED: 'is-selected'
  },
  KeyCodes: {
    ARROWDOWN: 40,
    ARROWLEFT: 37,
    ARROWRIGHT: 39,
    ARROWUP: 38,
    END: 35,
    HOME: 36,
    PAGEDOWN: 34,
    PAGEUP: 33,
    ASTERISK: 106,
    ENTER: 13,
    ESCAPE: 27,
    SPACE: 32,
    TAB: 9
  },
  Statuses: {
    AUTHOR_DRAFT: 'Author Draft',
    PREACCEPTANCE: 'Submitted',
    AT_PREPUB_CHECK: 'Pre-Publication Checks',
    PREPUB_AUTHORS: 'Revisions with Author',
    IN_EDITING: 'Author Revisions Received',
    READY_FOR_ML: 'Ready for Typesetters',
    SENT_TO_MC: 'Sent to Typesetters',
    BACK_FROM_TYPESETTERS: 'Back from Typesetters',
    AUTHOR_PDF_CHECK: 'PDF with Author',
    XML_PDF_REVISIONS: 'Returned to Typesetters',
    FINAL_CHECK_DONE: 'Final Check',
    READY_TO_PUBLISH: 'Ready to Publish',
    PUBLISHED: 'Published',
    UNDERGOING_PEER_REVIEW: 'Undergoing Peer Review',
    COMPLETED: 'Completed',
    PLAGIARISM: 'Enquiry with Authors',
    ON_HOLD: 'On Hold',
    SUGGEST_ARCHIVE: 'Suggest Archive',
    REJECTED: 'Rejected',
    WITHDRAWN: 'Withdrawn',
    REMOVED: 'Removed',
    RETRACTED: 'Retracted'
  },
};
