(function(){var d=document.getElementById("plx-css-details");if(!d){var q=document.head||document.getElementsByTagName("head")[0]||document.documentElement,d=document.createElement("link");d.setAttribute("id","plx-css-details");d.setAttribute("type","text/css");d.setAttribute("rel","stylesheet");d.setAttribute("href","//d39af2mgp1pqhg.cloudfront.net/details.css");q.appendChild(d)}})();
(function(){window.__plumX=window.__plumX||{};window.__plumX.widgets=window.__plumX.widgets||{};var d=__plumX.widgets;d.imageServiceUrl="//plumprint.plu.mx/image/v1/large";d.dataServiceUrl="//plumprint.plu.mx/widgets/v1";d.staticImagesUrl="//d39af2mgp1pqhg.cloudfront.net/2e9971b1fdcd89dc49349f95aa214ae5/"})();
(function e$$0(q,p,k){function m(a,f){if(!p[a]){if(!q[a]){var e="function"==typeof require&&require;if(!f&&e)return e(a,!0);if(l)return l(a,!0);e=Error("Cannot find module '"+a+"'");throw e.code="MODULE_NOT_FOUND",e;}e=p[a]={exports:{}};q[a][0].call(e.exports,function(e){var f=q[a][1][e];return m(f?f:e)},e,e.exports,e$$0,q,p,k)}return p[a].exports}for(var l="function"==typeof require&&require,g=0;g<k.length;g++)m(k[g]);return m})({1:[function(d,q,p){var k,m,l,g,a,f,e=function(c,b){return function(){return c.apply(b,
arguments)}},n=function(c,b){function a(){this.constructor=c}for(var e in b)h.call(b,e)&&(c[e]=b[e]);a.prototype=b.prototype;c.prototype=new a;c.__super__=b.prototype;return c},h={}.hasOwnProperty;m={socialMedia:"#13b7ea",citation:"#fd5704",usage:"#6dd54d",mention:"#f3c316",capture:"#c43bf3",background:"#6e1a62",ring:"#ffffff"};f={degToRad:function(c){return c*Math.PI/180},log2:function(c){return Math.log(c)/Math.LN2}};k={create:function(c){return(0<c.count?new k.NonEmptyAtom(c):new k.EmptyAtom(c)).serialize()}};
k.AtomBase=function(){function c(b){this.serialize=e(this.serialize,this);this.position=e(this.position,this);this.distance=e(this.distance,this);this.metric=b.metric;this.angle=b.angle;this.count=b.count;this.center=b.center}c.prototype.MIN_RADIUS=5;c.prototype.MAX_RADIUS=14;c.prototype.MIN_PADDING=5;c.prototype.MAX_PADDING=10;c.prototype.DISTANCE=14;c.prototype.isEmpty=function(){return null};c.prototype.radius=function(){return null};c.prototype.padding=function(){return null};c.prototype.distance=
function(){return this.DISTANCE+this.padding()};c.prototype.position=function(){var b,c,a;b=f.degToRad(this.angle);c=this.distance();a=Math.sin(b)*c+this.center.x;b=Math.cos(b)*c+this.center.y;return{x:a,y:b}};c.prototype.serialize=function(){var b;b=this.position();return{type:"atom",x:b.x,y:b.y,metric:this.metric,count:this.count,angle:this.angle,radius:this.radius(),distance:this.distance(),isEmpty:this.isEmpty()}};return c}();k.EmptyAtom=function(c){function b(){this.padding=e(this.padding,this);
this.radius=e(this.radius,this);return b.__super__.constructor.apply(this,arguments)}n(b,c);b.prototype.isEmpty=function(){return!0};b.prototype.radius=function(){return this.MIN_RADIUS-1};b.prototype.padding=function(){return this.MIN_PADDING-1};return b}(k.AtomBase);k.NonEmptyAtom=function(c){function b(){this.padding=e(this.padding,this);this.radius=e(this.radius,this);return b.__super__.constructor.apply(this,arguments)}n(b,c);b.prototype.isEmpty=function(){return!1};b.prototype.radius=function(){var b;
b=f.log2(this.count)+this.MIN_RADIUS;b>this.MAX_RADIUS&&(b=this.MAX_RADIUS);return b};b.prototype.padding=function(){var b;b=f.log2(this.count);b>this.MAX_PADDING&&(b=this.MAX_PADDING);return 1.3*b+this.MIN_PADDING};return b}(k.AtomBase);a=function(c){function b(c,a){this.generate=e(this.generate,this);this.controlPoints=e(this.controlPoints,this);this.mergePoints=e(this.mergePoints,this);this.serialize=e(this.serialize,this);this.serialize=e(this.serialize,this);b.__super__.constructor.call(this);
this.atoms=c;this.center=a;this.generate()}n(b,c);b.prototype.ANGLE_MOD=122;b.prototype.DIST_FACT=0.2;b.prototype.serialize=function(){var b;b=[].concat(this.path);b.type="shape";return b};b.prototype.serialize=function(){var b;b=[].concat(this.path);b.type="shape";return b};b.prototype.mergePoints=function(b){return[b.angle-125,b.angle+125].map(function(c){var a;a=f.degToRad(c);c=Math.sin(a)*b.radius+b.x;a=Math.cos(a)*b.radius+b.y;return{x:c,y:a}})};b.prototype.controlPoints=function(b){var c;c=
b.angle+180;return[c-this.ANGLE_MOD,c+this.ANGLE_MOD].map(function(b){return f.degToRad(b)}).map(function(c){return function(a){var e;e=Math.sin(a)*b.distance*c.DIST_FACT+c.center.x;a=Math.cos(a)*b.distance*c.DIST_FACT+c.center.y;return{x:e,y:a}}}(this))};b.prototype.generate=function(){var b,c,a,e,f,h,d,g,n,k;n=this.atoms.map(function(b){return function(c){return b.mergePoints(c)}}(this));b=this.atoms.map(function(b){return function(c){return b.controlPoints(c)}}(this));c=function(c){return b[c][0]};
h=function(c){return b[c][1]};a=function(b){return n[b][0]};g=function(b){return n[b][1]};d=this.atoms;e=f=0;for(d=d.length;f<d;e=++f)k=e+1>=this.atoms.length?0:e+1,0===e?this.start(g(e).x,g(e).y):this.line(g(e).x,g(e).y),this.cubic(h(e).x,h(e).y,c(k).x,c(k).y,a(k).x,a(k).y);return this.end()};return b}(function(){function c(){this.serialize=e(this.serialize,this);this.cubic=e(this.cubic,this);this.line=e(this.line,this);this.end=e(this.end,this);this.start=e(this.start,this);this.path=[]}c.prototype.start=
function(b,c){return this.path.push({type:"start",x:b,y:c})};c.prototype.end=function(){return this.path.push({type:"end"})};c.prototype.line=function(b,c){return this.path.push({type:"line",x:b,y:c})};c.prototype.cubic=function(b,c,a,e,f,h){return this.path.push({type:"cubic",cx1:b,cy1:c,cx2:a,cy2:e,x:f,y:h})};c.prototype.serialize=function(){var b;b=[];b.type="shape";b.concat(this.path);return b};return c}());g={create:function(c,b){return(new a(c,b)).serialize()}};d=function(){function c(b){this._createShape=
e(this._createShape,this);this._createAtoms=e(this._createAtoms,this);this.display_width=b.width||100;this.display_height=b.height||100;this.center={x:this.WIDTH/2,y:this.HEIGHT/2};this.order=this.METRICS.slice(0).reverse();this.step=360/this.METRICS.length}c.prototype.WIDTH=100;c.prototype.HEIGHT=100;c.prototype.METRICS=["usage","capture","mention","socialMedia","citation"];c.prototype["for"]=function(b){b=this._createAtoms(b);return[this._createShape(b)].concat(b)};c.prototype._createAtoms=function(b){var c,
a,e,f,h,d,g;c=[];g=this.order;e=f=0;for(h=g.length;f<h;e=++f)d=g[e],a=b[d]||0,c.push(k.create({metric:d,count:a,center:this.center,angle:this.step*(e-1)}));return c};c.prototype._createShape=function(b){return g.create(b,this.center)};return c}();l={atom:function(c,b){if(b.isEmpty)return c.circle({cx:b.x,cy:b.y,r:b.radius,fill:m.background,stroke:m.background});c.circle({cx:b.x,cy:b.y,r:b.radius,fill:m[b.metric],stroke:m.background});return c.circle({cx:b.x,cy:b.y,r:b.radius-1.5,fill:"none",stroke:m.ring,
strokeWidth:1.5})},shape:function(c,b){var a,e,f,h,d;f=c.path({fill:m.background,stroke:m.background,strokeWidth:0.9});h=[];a=0;for(e=b.length;a<e;a++)switch(d=b[a],d.type){case "start":h.push(f.start(d.x,d.y));break;case "end":h.push(f.close());break;case "line":h.push(f.line(d.x,d.y));break;case "cubic":h.push(f.cubic(d.cx1,d.cy1,d.cx2,d.cy2,d.x,d.y));break;default:h.push(void 0)}return h}};p=function(){function c(b){this.canvas=b;this.render=e(this.render,this)}c.prototype.render=function(b){var c,
a,e,f,h;h=[];c=0;for(a=b.length;c<a;c++)e=b[c],f=l[e.type],h.push(f(this.canvas,e));return h};return c}();d.Renderer=p;q.exports=d},{}],2:[function(d,q,p){var k,m,l=function(d,a){return function(){return d.apply(a,arguments)}};k=d("./resource");m=d("./statistics");d=function(){function d(a){this.handler=a;this._whenFail=l(this._whenFail,this);this._whenDone=l(this._whenDone,this);this.handleFail=l(this.handleFail,this);this.handleEmpty=l(this.handleEmpty,this);this.handleData=l(this.handleData,this);
this.fetch=l(this.fetch,this);this.stats=null}d.prototype.fetch=function(a){return k.artifact(a).done(this._whenDone).fail(this._whenFail)};d.prototype.handleData=function(){this.handler.stats(this.stats);return this.handler.callback.success()};d.prototype.handleEmpty=function(){this.handler.empty();return this.handler.callback.empty()};d.prototype.handleFail=function(){this.handler.fail();return this.handler.callback.fail()};d.prototype._whenDone=function(a){this.stats=m(a.statistics);return this.stats.isEmpty?
this.handleEmpty():this.handleData()};d.prototype._whenFail=function(a){return"NotFound"===a?this.handleEmpty():this.handleFail()};return d}();q.exports=d},{"./resource":13,"./statistics":14}],3:[function(d,q,p){var k,m,l,g,a,f=function(a,c){return function(){return a.apply(c,arguments)}},e=function(a,c){function b(){this.constructor=a}for(var e in c)n.call(c,e)&&(a[e]=c[e]);b.prototype=c.prototype;a.prototype=new b;a.__super__=c.prototype;return a},n={}.hasOwnProperty;l={"stroke-width":1,stroke:"black",
fill:"black"};g="http://www.w3.org/2000/svg";p=function(){function a(c){this.strokeWidth=f(this.strokeWidth,this);this.stroke=f(this.stroke,this);this.fill=f(this.fill,this);this.setAttr=f(this.setAttr,this);this.node=document.createElementNS(g,c)}a.prototype.setAttr=function(c,b){return this.node.setAttribute(c,null!=b?b:l[c])};a.prototype.fill=function(c){return this.setAttr("fill",c)};a.prototype.stroke=function(c){return this.setAttr("stroke",c)};a.prototype.strokeWidth=function(c){return this.setAttr("stroke-width",
c)};return a}();d=function(a){function c(b){c.__super__.constructor.call(this,b)}e(c,a);return c}(p);p=function(a){function c(b,a,e){c.__super__.constructor.call(this,a);b.appendChild(this.node);this.fill(e.fill);this.stroke(e.stroke);this.strokeWidth(e.strokeWidth)}e(c,a);return c}(p);m=function(a){function c(b,a){this.line=f(this.line,this);this.cubic=f(this.cubic,this);this.close=f(this.close,this);this.start=f(this.start,this);c.__super__.constructor.call(this,b,"path",a);this.path=[];this.started=
!1}e(c,a);c.prototype.start=function(b,c){this.path.push("M "+b+","+c);return this.started=!0};c.prototype.close=function(){this.path.push("Z");return this.setAttr("d",this.path.join(" "))};c.prototype.cubic=function(b,c,a,e,f,d){return this.path.push("C "+b+","+c+" "+a+","+e+" "+f+","+d)};c.prototype.line=function(b,c){return this.path.push("L "+b+","+c)};return c}(p);k=function(a){function c(b,a){this.position=f(this.position,this);this.radius=f(this.radius,this);c.__super__.constructor.call(this,
b,"circle",a);this.radius(a.r);this.position(a.cx,a.cy)}e(c,a);c.prototype.radius=function(b){return this.setAttr("r",b)};c.prototype.position=function(b,c){this.setAttr("cx",b);return this.setAttr("cy",c)};return c}(p);a=function(a){function c(b){this.circle=f(this.circle,this);this.path=f(this.path,this);c.__super__.constructor.call(this,"svg",b);this.setAttr("viewBox","0 0 100 100");this.setAttr("width",b.width);this.setAttr("height",b.height)}e(c,a);c.prototype.path=function(b){return new m(this.node,
b)};c.prototype.circle=function(b){return new k(this.node,b)};return c}(d);d={create:function(e){return new a(e)},supported:!!document.createElementNS&&!!document.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect};q.exports=d},{}],4:[function(d,q,p){q.exports=window.__plumX.widgets},{}],5:[function(d,q,p){var k,m,l,g,a,f,e,n,h,c=function(b,c){return function(){return b.apply(c,arguments)}};p=d("./loader");a=d("./util");k=d("./config");n=d("./dom");g=d("./translation");h=p.whenReady(function(b){return h=
b});l=["Usage","Captures","Mentions","Social Media","Citations"];e=a.categoryClass;f=function(){return n.div({"class":"ppd-branding"}).append(n.img({"class":"plx-logo",src:k.staticImagesUrl+"plumx-logo.png"})).append(n.span({text:" - "}))};m=function(){function b(b){this.scaffold=c(this.scaffold,this);this.seeMore=c(this.seeMore,this);this.footer=c(this.footer,this);this.href=b.href;this.orientation=b.orientation;this.details=b.details;this.print=b.print;this.width=b.width;this.border=!!b.border;
this.isEmpty=h.isEmptyObject(this.details);this.hasPrint=null!=this.print;this.hasWidth=!!this.width;this.minWidth=310;this.hasPrint&&(this.minWidth+=120);this.translation=new g(b.lang);this.trans=function(b){return function(c){return b.translation.translate(c)}}(this);this.scaffold();b.hover.bindTo(this.container)}b.prototype.categoryBox=function(b,c){var f,d,h,g,k,l,m;f=n.ul({"class":"ppd-box "+e(b)});f.append(n.li().append(n.div({"class":"ppd-title",text:this.trans(b)})));l=[];h=0;for(k=c.length;h<
k;h++)d=c[h],g=a.splitLabels(d.label,this.trans),g=n.span({"class":"ppd-label",text:g+": "}),m=null,d.link&&(m=d.link),d=m?n.a({"class":"ppd-count",href:m,target:"_blank",text:d.count}):n.span({"class":"ppd-count",text:d.count}),f.append(n.li().append(g).append(d)),l.push(f);return l};b.prototype.footer=function(){return n.div({"class":"ppd-footer"}).append(f()).append(this.seeMore())};b.prototype.seeMore=function(){return n.a({href:this.href,"class":"ppd-seemore",text:this.trans("see details")})};
b.prototype.emptyMessage=function(){return n.div({"class":"ppd-empty",text:this.trans("No metrics available.")})};b.prototype.scaffold=function(){var b,c,a,e,f,d,g;g=n.div({"class":"PlumX-Details"});g.css("min-width",this.minWidth);this.hasWidth&&g.css("width",this.width);c=n.div({"class":"ppd-container"});this.border&&c.addClass("ppd-border");d=n.div({"class":"ppd-rows"});b=n.a({"class":"plx-wrapping-print-link",href:this.href});this.hasPrint&&c.append(n.div({"class":"ppd-print-col"}).append(b.append(n.div({"class":"plx-print"}).append(this.print))));
f=n.div({"class":"ppd-row"});a=0;for(e=l.length;a<e;a++)b=l[a],h.isEmptyObject(this.details[b])||f.append(this.categoryBox(b,this.details[b]));this.isEmpty&&f.append(this.emptyMessage());d.append(f);d.append(this.footer);c.append(d);this.element=g.append(c);return this.container=c};return b}();q.exports=function(b){return(new m(b)).element}},{"./config":4,"./dom":6,"./loader":9,"./translation":16,"./util":17}],6:[function(d,q,p){var k,m,l,g,a,f;g=d("./loader").whenReady(function(a){return g=a});p=
["div","ul","li","span","img"];d={};k=function(a,f){var d,c,b;c=g("<"+a+">");for(d in f)b=f[d],"text"===d?c.text(b):"html"===d?c.html(b):c.attr(d,b);return c};m=function(a){return function(f){return k(a,f)}};l=0;for(a=p.length;l<a;l++)f=p[l],d[f]=m(f);d.a=function(a){return k("a",g.extend({target:"_blank"},a))};q.exports=d},{"./loader":9}],7:[function(d,q,p){var k,m,l,g,a,f,e=function(c,b){return function(){return c.apply(b,arguments)}},n=function(c,b){function a(){this.constructor=c}for(var e in b)h.call(b,
e)&&(c[e]=b[e]);a.prototype=b.prototype;c.prototype=new a;c.__super__=b.prototype;return c},h={}.hasOwnProperty;l=d("./loader");p=d("./config");g=d("./dom");k=l.whenReady(function(c){return k=c});m=p.dataServiceUrl+"/event";a=function(){var c;c=k("#plx-evt-trspt");return c.length?c:g.img({id:"plx-evt-trspt"}).css({display:"none"}).appendTo("body")};f=function(c){return a().attr({src:m+"?"+k.param(c)})};d=function(c){function b(){this._endHover=e(this._endHover,this);this._startHover=e(this._startHover,
this);this._clearTimer=e(this._clearTimer,this);this.logEvent=e(this.logEvent,this);this.bindTo=e(this.bindTo,this);return b.__super__.constructor.apply(this,arguments)}n(b,c);b.prototype.timeout=1E3;b.prototype.eventName="hover";b.prototype.bindTo=function(b){return b.on("mouseenter",this._startHover).on("mouseleave",this._endHover)};b.prototype.logEvent=function(){return this.log()};b.prototype._clearTimer=function(){if(this.timer)return clearTimeout(this.timer),this.timer=null};b.prototype._startHover=
function(){this._clearTimer();return this.timer=setTimeout(this.logEvent,this.timeout)};b.prototype._endHover=function(){return this._clearTimer()};return b}(function(){function c(b){this.options=b;this.log=e(this.log,this)}c.prototype.log=function(b){null==b&&(b={});return f(k.extend({event:this.eventName},this.options,b))};c.prototype.logEvent=function(){};return c}());q.exports={Hover:d}},{"./config":4,"./dom":6,"./loader":9}],8:[function(d,q,p){var k,m,l,g=function(a,f){return function(){return a.apply(f,
arguments)}};l=function(a){var f,e;if(a){e=a.split(".").reverse();for(a=window[e.pop()];a&&(f=a[e.pop()]);)a=f;return a}};m=function(a,f){return function(a,f){return a?function(){var d;if(d=l(a))return d(f.elem())}:function(){}}(a,f)};k=function(){return function(a){var f,e;this.handler=a;e=this.handler.callbacks;for(f in e)a=e[f],this[f]=m(a,this.handler)}}();d=function(){function a(a,e){this.placeholder=a;this.options=e;this.fail=g(this.fail,this);this.elem=g(this.elem,this);this.remove=g(this.remove,
this);this.render=g(this.render,this);this.callbacks={success:this.options.onSuccess,empty:this.options.onEmpty,fail:this.options.onFail};this.callback=new k(this)}a.prototype.render=function(a){a=this.renderer(a);this.placeholder.replaceWith(a);return this.placeholder=a};a.prototype.remove=function(){return this.placeholder.hide().removeClass()};a.prototype.elem=function(){return this.placeholder.get(0)};a.prototype.fail=function(){return this.remove()};return a}();q.exports=d},{}],9:[function(d,
q,p){var k,m,l,g,a,f;k=null;l=[];f=function(){return k(document).ready(function(a){var f,d,c,b;b=[];d=0;for(c=l.length;d<c;d++)f=l[d],b.push(f(a));return b})};m=function(a){return(document.head||document.getElementsByTagName("head")[0]||document.documentElement).appendChild(a)};a=function(a){var f;f=document.createElement("script");f.setAttribute("type","text/javascript");f.setAttribute("src",a);return f};p=function(){var e;e=a("//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js");e.readyState?
e.onreadystatechange=function(){if("complete"===this.readyState||"loaded"===this.readyState)return g()}:e.onload=g;return m(e)};d=function(a){a=a.split(".");return"1"!==a[0]?!1:8<=parseInt(a[1],10)?!0:!1};g=function(){k=window.jQuery.noConflict(!0);return f()};null!=window.jQuery&&d(window.jQuery.fn.jquery)?(k=window.jQuery,f()):p();q.exports={whenReady:function(a){return"undefined"!==typeof isReady&&null!==isReady?a(k):l.push(a)}}},{}],10:[function(d,q,p){d=function(){for(var d=[],m=0;64>m;)d[m]=
0|4294967296*Math.abs(Math.sin(++m));return function(l){var g,a,f,e,n=[];l=unescape(encodeURI(l));for(var h=l.length,c=[g=1732584193,a=-271733879,~g,~a],b=0;b<=h;)n[b>>2]|=(l.charCodeAt(b)||128)<<8*(b++%4);n[l=16*(h+8>>6)+14]=8*h;for(b=0;b<l;b+=16){h=c;for(e=0;64>e;)h=[f=h[3],(g=h[1]|0)+((f=h[0]+[g&(a=h[2])|~g&f,f&g|~f&a,g^a^f,a^(g|~f)][h=e>>4]+(d[e]+(n[[e,5*e+1,3*e+5,7*e][h]%16+b]|0)))<<(h=[7,12,17,22,5,9,14,20,4,11,16,23,6,10,15,21][4*h+e++%4])|f>>>32-h),g,a];for(e=4;e;)c[--e]=c[e]+h[e]}for(l="";32>
e;)l+=(c[e>>3]>>4*(1^e++&7)&15).toString(16);return l}}();q.exports=d},{}],11:[function(d,q,p){p=d("./config");d=d("./util");p.pageToken||(p.pageToken=d.guid());q.exports=p.pageToken},{"./config":4,"./util":17}],12:[function(d,q,p){var k,m,l,g,a,f,e,n,h,c;l=d("./print");k=d("./canvas");p=d("./loader");g=d("./util");m=d("./config");a=d("./dom");f=p.whenReady(function(b){return f=b});c=g.shortenKeys;h=function(b){var a,c;a={width:"100%",height:"100%"};c=new l(a);a=k.create(a);b=c["for"](b);(new l.Renderer(a)).render(b);
return a.node};n=function(b){b=f.param(c(b));return a.img({src:m.imageServiceUrl+"?"+b})};e=function(b){b=g.camelizeKeys(b);return k.supported?h(b):n(b)};e.empty=function(){return e({})};e["for"]=function(b){return e(b)};q.exports=e},{"./canvas":3,"./config":4,"./dom":6,"./loader":9,"./print":1,"./util":17}],13:[function(d,q,p){var k,m,l,g,a,f,e,n,h,c,b=function(b,a){return function(){return b.apply(a,arguments)}},r=[].indexOf||function(b){for(var a=0,c=this.length;a<c;a++)if(a in this&&this[a]===
b)return a;return-1};g=d("./loader");m=d("./config");p=d("./util");h=d("./md5");n=g.whenReady(function(b){return n=b});k=m.dataServiceUrl;l={cache:!0,ifModified:!0,dataType:"jsonp"};e=function(b){return setTimeout(b,10)};f=function(){function a(){this.put=b(this.put,this);this.has=b(this.has,this);this.get=b(this.get,this);this.items=[]}a.prototype.get=function(b){return this.items[b]};a.prototype.has=function(b){return 0<=r.call(this.items,b)};a.prototype.put=function(b,a){return this.items[b]=a};
return a}();a=function(){function a(){this.emit=b(this.emit,this);this.unsubscribe=b(this.unsubscribe,this);this.subscribe=b(this.subscribe,this);this.publish=b(this.publish,this);this.subscribersForHash=b(this.subscribersForHash,this);this.addSubscriber=b(this.addSubscriber,this);this.hasSubscription=b(this.hasSubscription,this);this.store=new f;this.subscribers={}}a.prototype.hasSubscription=function(b,a){return-1!==this.subscribersForHash(b).indexOf(a)};a.prototype.addSubscriber=function(b,a){return this.subscribersForHash(b).push(a)};
a.prototype.subscribersForHash=function(b){var a;(a=this.subscribers)[b]||(a[b]=[]);return this.subscribers[b]};a.prototype.publish=function(b,a){this.store.has(b)||this.store.put(b,a);return this.emit(b)};a.prototype.subscribe=function(b,a){var c;this.hasSubscription(b,a)||this.addSubscriber(b,a);c=function(c){return function(){return c.unsubscribe(b,a)}}(this);e(function(a){return function(){if(a.store.has(b))return a.emit(b)}}(this));return c};a.prototype.unsubscribe=function(b,a){var c,e;e=this.subscribersForHash(b);
c=e.indexOf(a);if(-1===c)return!1;e.splice(c,1);return!0};a.prototype.emit=function(b){var a,c,e,f,d,h,g;d=this.subscribersForHash(b);h=[];c=0;for(e=d.length;c<e;c++)f=d[c],g=this.store.get(b),f&&g?(a=g.error_code)?h.push(f.reject(a)):h.push(f.resolve(g)):h.push(void 0);return h};return a}();c=function(b){return n.extend({},l,b)};d=function(b){return function(a){var e,f,d,g;f=h(b+"---"+a.id+"---"+(a.site||""));e="plum"+f;a=n.param(a);e=c({url:k+"/"+b+"?"+a,jsonpCallback:e});d=window.__plumX.widgets.responses.store;
a=n.Deferred();g=d.subscribe(f,a);a.always(g);n.ajax(e).done(function(b,a,c){return d.publish(f,b)});return a}};p.withGlobalNS("__plumX.widgets.responses",function(b){return b.store=new a});q.exports={artifact:d("artifact"),researcher:d("researcher"),group:d("group"),grant:d("grant")}},{"./config":4,"./loader":9,"./md5":10,"./util":17}],14:[function(d,q,p){var k,m,l,g,a,f,e,n=function(a,c){return function(){return a.apply(c,arguments)}};l=function(a){var c,b,e,f,d;c={};b=0;for(f=a.length;b<f;b++)e=
a[b],c[d=e.label]||(c[d]=0),e.count>c[e.label]&&(c[e.label]=e.count);return c};m=function(a){var c,b,e,f,d;c={};b=0;for(f=a.length;b<f;b++)e=a[b],c[d=e.label]||(c[d]=0),c[e.label]+=e.count;return c};g=function(a){var c;c=document.createElement("a");c.href=a;return c.hostname};e=function(a){var c;if(a.refId&&(c=g(a.refId)))a.label=c;return f(a)};f=function(a){var c;c={label:a.source+" - "+a.label,count:a.count};a.link&&(c.link=a.link);return c};a=function(a){return({Twitter:e}[a.source]||f)(a)};k=
function(){function e(a){this._isEmpty=n(this._isEmpty,this);this._total=n(this._total,this);this.details=n(this.details,this);this.summary=n(this.summary,this);this.aggrCounts=n(this.aggrCounts,this);this.data=a;this.isEmpty=this._isEmpty()}e.prototype.aggrCounts=function(){var a,b,e,f,d,g,k,h;e={};h=this.data;for(a in h){g=h[a];f=b=0;for(k=g.length;f<k;f++)d=g[f],b+=d.count;e[a]=b}return e};e.prototype.summary=function(){var a,b,e,f;if(this.isEmpty)return{};f={};e=this.data;for(a in e)b=e[a],f[a]=
"Citations"===a?l(b):m(b);return f};e.prototype.details=function(){var c,b,e,f,d,g,h;if(this.isEmpty)return{};b={};h=this.data;for(c in h){d=h[c];b[c]=[];e=0;for(g=d.length;e<g;e++)f=d[e],b[c].push(a(f))}return b};e.prototype._total=function(){var a,b,e,f,d,g,h;h=0;g=this.data;for(a in g){f=g[a];b=0;for(d=f.length;b<d;b++)e=f[b],h+=e.count}return h};e.prototype._isEmpty=function(){return 0===this._total()};return e}();q.exports=function(a){return new k(a)}},{}],15:[function(d,q,p){q.exports={es:{"Abstract Views":"Vistas de Resumen",
Abstract:"Resumen","Affiliated Researchers":"Investigadores Afiliados",Article:"Art\u00edculo","Artifact Summary":"Resumen Productos de Investigaci\u00f3n",Audio:"Audio",Bibliography:"Bibliography","Blog Mentions":"Menciones Blog","Blog Post":"Comentarios de Blog",Blog:"Blog","Book Chapter":"Cap\u00edtulo de Libro",Book:"Libro",Bookmarks:"Marcadores",Brief:"Compendio",Captures:"Capturas",Case:"Caso",Catalogue:"Cat\u00e1logo","Citation Indexes":"\u00cdndice de Citas",Citations:"Citas",Clicks:"Clics",
"Clinical Citations":"Citas Cl\u00ednicas","Clinical Trial":"Ensayo Cl\u00ednico",Code:"C\u00f3digo",Collaborators:"Colaboradores",Collection:"Coleci\u00f3n",Comments:"Comentarios","Conference Paper":"Memorias de Congresos",Correction:"Correcci\u00f3n","Data Set":"Conjunto de Datos","Data Views":"Vistas Apoyadas","Design/Architecture":"Dise\u00f1o / Arquitectura",Downloads:"Descargas","Economic Blog Mentions":"Mentciones Blogs Econ\u00f3micos","Exhibition/Event":"Exhibici\u00f3n/Evento","Expert Opinion":"Opini\u00f3n de Experto",
"Exports-Saves":"Exportados / Guardados",Favorites:"Favoritos",Figure:"Cifra","File Set":"Conjunto de Archivos",Followers:"Seguidores",Forks:"Conexiones","Forum Topics":"Conteo Temas Foro","Full Text Views":"Vistas Txt Completo",Gists:"Conteo Esencial","Government Document":"Documento de Gobierno",Grant:"Beca","HTML Views":"Vistas HTML",Holdings:"Acervo",Image:"Imagen",Interview:"Entrevista",Issue:"N\u00famero",Journal:"Publicaci\u00f3n",Letter:"Ensayo",Likes:"Me Gusta","Link-outs":"V\u00ednculos",
Links:"Enlaces","Live Performance":"Presentaci\u00f3n en Vivo",Manuscript:"Manuscrito",Map:"Mapa",Media:"Medios",Mentions:"Menciones","Music Score":"Partitura Musical","News Mentions":"Menciones Noticias",News:"Noticias",Newsletter:"Bolet\u00edn Informativo","No metrics available.":"No hay m\u00e9tricas disponibles.","Online Course":"Curso en l\u00ednea",Other:"Otro","PDF Views":"Vistas PDF",Paper:"Documento de Trabajo","Patent Citations":"Citas de Patentes",Patent:"Patentes",Plays:"Reproducciones",
Policy:"Pol\u00edticas",Poster:"Afiche",Preprint:"Preimpresi\u00f3n",Presentation:"Presentaci\u00f3n",Project:"Proyecto",Ratings:"Clasificaci\u00f3n",Readers:"Lectores","Recent Artifacts":"Piezas de Investigaci\u00f3n Recientes",Recommendations:"Recomendaciones","Recorded Work":"Grabaci\u00f3n","Reference Entry":"Referencia",Report:"Informe",Researchers:"Investigadores",Retraction:"Retracci\u00f3n",Review:"Cr\u00edticas","Sample Downloads":"Descarga del Ejemplo",Scores:"Calificaci\u00f3n",Shares:"Compartir",
"Social Media":"Redes Sociales",Speech:"Discurso",Standard:"Est\u00e1ndar",Subscribers:"Subscriptores",Syllabus:"Plan de Estudios","Textual Work":"Escrito","Thesis / Dissertation":"Tesis / Disertaci\u00f3n",Tweets:"Tuits",Unknown:"Desconocido",Usage:"Uso",Video:"Video",Views:"Vistas","Visual Arts":"Artes Visuales",Volume:"Volumen",Watchers:"Observadores","Web Page":"P\u00e1gina Web","Web Resource":"Recurso Web","see details":"Ver detalles","Brochure / Pamphlet":"Folleto / Panfleto",Commentary:"Comentario",
Editorial:"Editorial","Research Proposal":"Propuesta de Investigaci\u00f3n","Technical Documentation":"Documento T\u00e9cnico","Code / Software":"C\u00f3digo / Software","Lecture / Presentation":"Presentaci\u00f3n","Learning Object":"objetos de aprendizaje","Research Artifact":"Pieza Investigativa"}}},{}],16:[function(d,q,p){var k,m;m=d("./stringLibrary");k="en";d=function(){function d(g,a){this.language=null!=g?g:k;this.options=null!=a?a:{};this.stringLib=m;this.notDefaultLanguage=this.language!==
k;this.stringLib.hasOwnProperty(k)||(this.stringLib[k]={});this}d.prototype.translate=function(d){return!this.notDefaultLanguage?d:this.dictionary().hasOwnProperty(d)&&this.dictionary()[d].length?this.dictionary()[d]:d};d.prototype.dictionary=function(){return this.stringLib.hasOwnProperty(this.language)?this.stringLib[this.language]:this.stringLib[k]};return d}();q.exports=d},{"./stringLibrary":15}],17:[function(d,q,p){var k,m,l,g;g=d("./loader").whenReady(function(a){return g=a});m=function(a){a=
a.split("&");a=g.map(a,function(a){return[a.split("=",2)]});a=g.grep(a,function(a){return"ebsco-client"!==a[0]});a=a[0];return{type:a[0],id:a[1]}};l=function(a){a=a.split("/");return{type:"plumx_id",id:a[a.length-1]}};k={globalNS:function(a,f){var e,d,g,c,b;e=window;b=a.split(".");d=0;for(g=b.length;d<g;d++)c=b[d],e[c]||(e[c]={}),e=e[c];f&&f(e);return e},hasGlobalNS:function(a){var f,e,d,g;f=window;g=a.split(".");a=0;for(e=g.length;a<e;a++)if(d=g[a],d in f)f=f[d];else return!1;return!0},withGlobalNS:function(a,
d){return k.hasGlobalNS(a)?!1:k.globalNS(a,d)},camelize:function(a){a=a.split(" ");a[0]=a[0].toLowerCase();return k.singularize(a.join(""))},singularize:function(a){return a.replace(/s$/,"")},camelizeKeys:function(a){var d,e,g,h;e={};for(d in a)h=a[d],g=k.singularize(k.camelize(d)),e[g]=h;return e},shortenKeys:function(a){var d,e,g;e={};for(d in a)g=a[d],e[d.substr(0,2)]=g;return e},chunk:function(a,d){var e,g,h,c;c=[];h=Math.ceil(a.length/d);for(e=g=0;0<=h?g<h:g>h;e=0<=h?++g:--g)c.push(a.slice(e*
d,(e+1)*d));return c},categoryClass:function(a){return"plx-"+k.singularize(k.camelize(a))},artifactIdFromUrl:function(a){a=a.split("?",2);return 1<a.length?m(a[1]):l(a[0])},isSitePrefixed:function(a){a=a.split("/");return-1!==["u","a","g","grant"].indexOf(a[4])},resourceIdFromUrl:function(a){var d;d=a.split("?");if(1<d.length)return d=d[1].split("="),a=d[0],d=d[1],{type:a,id:d};d=k.isSitePrefixed(a)?5:4;d=a.split("/").slice(d).join(".");return{type:"plumx_id",id:d}},grantIdFromUrl:function(a){a=a.split("/");
return{type:"plumx_id",id:a[a.length-1]}},guid:function(){var a,d;a=function(){return Math.floor(65536*(1+Math.random())).toString(16).substring(1)};d=function(){return a()+a()};return[d(),a(),a(),a(),a(),d()+a()].join("-")},splitLabels:function(a){return function(a,d){null==d&&(d=function(a){return a});a=a.split(" - ");return 1===a.length?d(a[0]):2===a.length?[a[0],d(a[1])].join(" - "):d(a.join(" - "))}}(this)};q.exports=k},{"./loader":9}],18:[function(d,q,p){var k,m,l=function(d,a){return function(){return d.apply(a,
arguments)}};k=d("./util");p=function(d){return k.resourceIdFromUrl(d.href)};d=function(d){return k.grantIdFromUrl(d.href)};d=function(d){return{type:"plumx_id",id:d.href.split("/").pop()}};m={artifact:function(d){return k.artifactIdFromUrl(d.href)},group:function(d){return d.gp?{type:"plumx_id",id:d.gp}:k.resourceIdFromUrl(d.href)},grant:d,researcher:p,person:p};d=function(){function d(a,f){this.placeholder=a;this.resourceType=f;this.getOptions=l(this.getOptions,this);this.getParams=l(this.getParams,
this);this.widget=this.getOptions();this.request=this.getParams()}d.prototype.getParams=function(){var a,d,e,g;d=m[this.resourceType](this.widget);e=this.widget;for(a in e)g=e[a],d[a]=g;d.ref=document.referrer;delete d.gp;return d};d.prototype.getOptions=function(){var a;a=this.placeholder.data();a.href=this.placeholder.attr("href");return a};return d}();q.exports=d},{"./util":17}],19:[function(d,q,p){var k,m,l,g,a,f,e,n,h,c,b=function(a,b){return function(){return a.apply(b,arguments)}},r=function(a,
b){function c(){this.constructor=a}for(var d in b)s.call(b,d)&&(a[d]=b[d]);c.prototype=b.prototype;a.prototype=new c;a.__super__=b.prototype;return a},s={}.hasOwnProperty;g=d("./lib/loader");k=d("./lib/artifact");e=d("./lib/plumprint");m=d("./lib/details");q=d("./lib/handler");p=d("./lib/util");a=d("./lib/widget_options");l=d("./lib/events");f=d("./lib/page_token");h=g.whenReady(function(a){return h=a});n=function(a){function c(){this.empty=b(this.empty,this);this.stats=b(this.stats,this);return c.__super__.constructor.apply(this,
arguments)}r(c,a);c.prototype.renderer=m;c.prototype.stats=function(a){var b;b={details:a.details()};this.options.hidePrint||(b.print=e["for"](a.aggrCounts()));return this.render(h.extend({},this.options,b))};c.prototype.empty=function(){var a;if(this.options.hideWhenEmpty)return this.remove();a={details:{}};this.options.hidePrint||(a.print=e.empty());return this.render(h.extend({},this.options,a))};return c}(q);c=function(){return h(".plumx-details").each(function(){var b,c;b=h(this);c=new a(b,"artifact");
c.request.widget="details";c.request.pageToken=f;c.widget.hover=new l.Hover(c.request);b=new n(b,c.widget);return(new k(b)).fetch(c.request)})};p.withGlobalNS("__plumX.widgets.details",function(a){a.wireUp=c;return g.whenReady(c)})},{"./lib/artifact":2,"./lib/details":5,"./lib/events":7,"./lib/handler":8,"./lib/loader":9,"./lib/page_token":11,"./lib/plumprint":12,"./lib/util":17,"./lib/widget_options":18}]},{},[19]);
