(function(){function g(a){this.a=a;this.f=null;this.h="hidden";this.b=0;this.c=[2E3,5E3,1E4,3E4,6E4];this.j=this.g=0;this.i="es ar cs de fr it ja ko nl pl pt ro ru th tr zh zh_TW id vi pt_BR zh-cn hi".split(" ")}
g.prototype.s=function(){k(this,l(this,1))};
g.prototype.l=function(a){if(a=m(1!==a.target.nodeType?a.target.parentNode:a.target)){if(-1!=a.href.indexOf("support.google.com")){var b=(new Date).getTime(),c=n(this);if(c&&!(c.time+this.a.vttl<b)&&this.f){var b=a.search,c=encodeURIComponent("vid"),d=encodeURIComponent(this.f),f=new RegExp("([?&]"+c.replace(/[-\/\\^$*+?.()|[\]{}]/g,"\\$&")+"=)([^&]*)"),b=f.test(b)?b.replace(f,"$1"+d.replace("$","$$")):b?b+"&"+c+"="+d:"?"+c+"="+d;a.search=b}}a=a.href;b=l(this,4);c=b.resource.stats[0].click_tracking=
{click_method:3,type:50};a&&(c.id=a);k(this,b)}};
function m(a){if(!a)return null;for(;a;){if("A"===a.tagName)return a;a=a.parentNode}return null}
function l(a,b){var c=a.a.pid;return{common_params:{language:a.a.hl,context_params:{referer:a.a.referer||document.a,request_source:10,request_url:a.a.rurl||window.location.href,visit_id:a.f,page_type:"forum"==c?0:"topic"===c.substr(0,5)?22:100}},resource:{stats:[{type:b,request_state:{initial_request_origin:1,page_id:a.a.pid}}]}}}
function p(a,b){var c=a.length-b.length,d=a.lastIndexOf(b,c);return-1!==d&&d===c}
function k(a,b){var c=new XMLHttpRequest;c.open("POST","https://support.google.com/apis/gpf_metrics?v=1&forum="+a.a.forumName);c.withCredentials=!0;c.send(JSON.stringify(b))}
function n(a){var b=window.localStorage;if(!b)return null;try{var c=b.getItem("vid-"+a.a.forumName);return c?JSON.parse(c):null}catch(d){return null}}
g.prototype.m=function(){document[this.h]?this.b&&(this.j=this.g-Date.now(),window.clearTimeout(this.b),this.b=0):!this.b&&0<this.c.length&&q(this,this.j)};
function q(a,b){a.g=Date.now()+b;a.b=window.setTimeout(a.o.bind(a),b)}
g.prototype.o=function(){var a=l(this,6);a.resource.stats[0].time_on_page={top:this.c[0]/1E3};k(this,a);a=this.c.shift();0<this.c.length?q(this,this.c[0]-a):this.b=0};
window.scGpf_initStats=function(a){a=new g(a);var b="en",c=a.a.forum;p(c,"+private")&&(c=c.substr(0,c.length-8));for(var d=0;d<a.i.length;d++){var f=a.i[d];if(p(c,"-"+f)){b=f;c=c.substr(0,c.length-(1+f.length));break}}a.a.hl=b;a.a.forumName=c;window.sc_gpf_metrics_init?0<a.b&&(window.clearTimeout(a.b),a.b=0):(document.getElementsByTagName("body")[0].addEventListener("click",a.l.bind(a)),window.sc_gpf_metrics_init=!0);var e;if((b=document.cookie)&&-1!=b.indexOf("SUPPORT_CONTENT"))try{a.f=b.split("SUPPORT_CONTENT")[1].split(";")[0].split("|")[1]}catch(r){}(b=
n(a))?e=b.visit_id:e=(a.a.li?"1":"0")+"-"+Math.floor(Math.random()*Date.now())+"-"+Date.now();if(b=window.localStorage){c={visit_id:e,time:(new Date).getTime()};try{var h=JSON.stringify(c);b.setItem("vid-"+a.a.forumName,h)}catch(r){}}a.f=e;e="";h=["moz","ms","webkit"];for(b=0;b<h.length;b++){e=h[b];c=e+"Hidden";if("undefined"!=typeof document[c]){a.h=c;break}e=""}document.addEventListener(e+"visibilitychange",a.m.bind(a));q(a,a.c[0]);window.scGpf_trackStatsPageView=a.s.bind(a)};}).call(this);
